# Change these first
owner: olmloa # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Cyber Services Supply
    url: https://cyberservicess.com/
  - name: Distribuidora Vit
    url: https://distribuidoravit.com
  - name: Panama Shopping Import
    url: https://panamashoppingimport.com
    maxResponseTime: 7000
  - name: Framart Group
    url: https://framartgroup.com
  - name: MediaNet
    url: https://medianet-pa.com
  - name: TecniDental
    url: https://tecnidentalpa.com
  - name: Bits Hits Radio
    url: https://bitshitsradio.com
    

status-website:
  theme: ocean
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: webstatus.thecyberss.com
  baseUrl: /
  # logoUrl: https://cyberservicess.com/logo1.png
  name: Estado de Sitios Web
  introTitle: "**WebStatus** es el monitor de tiempo de actividad de código abierto y la página de estado, impulsado completamente por GitHub."
  introMessage: Bienvenidos a nuestro portal de uptime o tiempo de vida de nuestros sitios web. Aquí podrá saber cuando tiempo estuvo al aire su sitio web desarrollados por nuestro equipo de desarrolladores.
  navbar:
    - title: Estado
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
